{
  "dataset": "countries_S1",
  "framework": "tensorflow",
  "iterations": 10,
  "status": "error",
  "error": "WARNING:tensorflow:From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/compat/v2_compat.py:98: disable_resource_variables (from tensorflow.python.ops.resource_variables_toggle) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n07/16/2025 07:21:55 PM: [ reading vocab files... ]\n07/16/2025 07:21:55 PM: [ Reading mid to name map ]\n07/16/2025 07:21:55 PM: [ Done.. ]\n07/16/2025 07:21:55 PM: [ Total number of entities 273 ]\n07/16/2025 07:21:55 PM: [ Total number of relations 6 ]\n07/16/2025 07:21:55 PM: [ Creating TF graph... ]\nWARNING:tensorflow:From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py:1260: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse `tf.random.categorical` instead.\n07/16/2025 07:21:55 PM: [ From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py:1260: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse `tf.random.categorical` instead. ]\nWARNING:tensorflow:From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py:1260: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse `tf.cast` instead.\n07/16/2025 07:21:55 PM: [ From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py:1260: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse `tf.cast` instead. ]\nWARNING:tensorflow:From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py:1260: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nDeprecated in favor of operator or tf.math.divide.\n07/16/2025 07:21:56 PM: [ From /opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py:1260: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nDeprecated in favor of operator or tf.math.divide. ]\n07/16/2025 07:21:56 PM: [ TF Graph creation done.. ]\nWARNING: All log messages before absl::InitializeLog() is called are written to STDERR\nI0000 00:00:1752690116.214103 67779625 mlir_graph_optimization_pass.cc:425] MLIR V1 optimization pass is not enabled\nWARNING:tensorflow:From /Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py:224: BaseSession.partial_run_setup (from tensorflow.python.client.session) is deprecated and will be removed after 2023-06-01.\nInstructions for updating:\nThis function is deprecated and we do not expect adding newfunctionality to it. Please do not have your code dependingon this function.\n07/16/2025 07:21:56 PM: [ From /Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py:224: BaseSession.partial_run_setup (from tensorflow.python.client.session) is deprecated and will be removed after 2023-06-01.\nInstructions for updating:\nThis function is deprecated and we do not expect adding newfunctionality to it. Please do not have your code dependingon this function. ]\nWARNING:tensorflow:From /Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py:236: BaseSession.partial_run (from tensorflow.python.client.session) is deprecated and will be removed after 2023-06-01.\nInstructions for updating:\nThis function is deprecated and we do not expect adding newfunctionality to it. Please do not have your code dependingon this function.\n07/16/2025 07:21:56 PM: [ From /Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py:236: BaseSession.partial_run (from tensorflow.python.client.session) is deprecated and will be removed after 2023-06-01.\nInstructions for updating:\nThis function is deprecated and we do not expect adding newfunctionality to it. Please do not have your code dependingon this function. ]\n2025-07-16 19:21:56.410910: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: CANCELLED: PRun cancellation\n2025-07-16 19:21:56.410933: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.410935: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.410938: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.410940: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.410943: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.410944: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.410946: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.410948: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.410949: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.410950: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    1, num_hits: 15.0000, avg. reward per batch  0.0469, num_ep_correct   11, avg_ep_correct  0.3438, train loss -0.0040 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 898056192 (kb) ]\n2025-07-16 19:21:56.483597: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: CANCELLED: PRun cancellation\n2025-07-16 19:21:56.483613: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.483615: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.483618: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.483619: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.483622: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.483623: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.483624: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.483626: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.483627: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.483628: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    2, num_hits: 54.0000, avg. reward per batch  0.1688, num_ep_correct   18, avg_ep_correct  0.5625, train loss -0.0133 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 905166848 (kb) ]\n2025-07-16 19:21:56.550874: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.550885: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.550888: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.550890: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.550892: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.550893: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.550894: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.550895: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.550896: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.550898: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    3, num_hits: 25.0000, avg. reward per batch  0.0781, num_ep_correct   13, avg_ep_correct  0.4062, train loss -0.0178 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 908836864 (kb) ]\n2025-07-16 19:21:56.617789: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: CANCELLED: PRun cancellation\n2025-07-16 19:21:56.617808: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.617811: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.617813: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.617815: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.617818: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.617820: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.617821: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.617822: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.617824: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.617825: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    4, num_hits: 20.0000, avg. reward per batch  0.0625, num_ep_correct   14, avg_ep_correct  0.4375, train loss -0.0212 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 911032320 (kb) ]\n2025-07-16 19:21:56.684276: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.684290: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.684293: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.684295: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.684297: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.684299: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.684300: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.684301: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.684302: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.684303: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    5, num_hits: 41.0000, avg. reward per batch  0.1281, num_ep_correct   12, avg_ep_correct  0.3750, train loss -0.0304 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 914210816 (kb) ]\n2025-07-16 19:21:56.751269: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.751283: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.751285: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.751287: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.751290: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.751291: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.751292: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.751293: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.751294: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.751295: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    6, num_hits: 36.0000, avg. reward per batch  0.1125, num_ep_correct   11, avg_ep_correct  0.3438, train loss -0.0372 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 917192704 (kb) ]\n2025-07-16 19:21:56.818552: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.818566: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.818569: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.818571: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.818574: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.818575: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.818577: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.818578: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.818580: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.818581: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    7, num_hits: 37.0000, avg. reward per batch  0.1156, num_ep_correct   12, avg_ep_correct  0.3750, train loss -0.0431 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 919568384 (kb) ]\n2025-07-16 19:21:56.887508: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: CANCELLED: PRun cancellation\n2025-07-16 19:21:56.887525: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.887526: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.887530: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.887532: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.887534: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.887536: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.887538: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.887539: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.887540: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.887542: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    8, num_hits: 49.0000, avg. reward per batch  0.1531, num_ep_correct   19, avg_ep_correct  0.5938, train loss -0.0506 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 921583616 (kb) ]\n2025-07-16 19:21:56.958239: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:56.958249: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:56.958252: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:56.958253: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:56.958256: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:56.958257: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:56.958259: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:56.958261: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:56.958262: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:56.958263: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:56 PM: [ batch_counter:    9, num_hits: 40.0000, avg. reward per batch  0.1250, num_ep_correct   17, avg_ep_correct  0.5312, train loss -0.0558 ]\n07/16/2025 07:21:56 PM: [ Memory usage: 925827072 (kb) ]\n2025-07-16 19:21:57.029479: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 17010893853768107008\n2025-07-16 19:21:57.029492: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 12312384304662971617\n2025-07-16 19:21:57.029495: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 1927757129552768241\n2025-07-16 19:21:57.029497: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 16663506164284321222\n2025-07-16 19:21:57.029499: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 5924132018715644282\n2025-07-16 19:21:57.029501: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 10522314409757013103\n2025-07-16 19:21:57.029502: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 11853790656145422007\n2025-07-16 19:21:57.029504: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 14350653934551800738\n2025-07-16 19:21:57.029505: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 2844368814522170714\n2025-07-16 19:21:57.029507: I tensorflow/core/framework/local_rendezvous.cc:430] Local rendezvous send item cancelled. Key hash: 4080339137497464457\n07/16/2025 07:21:57 PM: [ batch_counter:   10, num_hits: 46.0000, avg. reward per batch  0.1437, num_ep_correct   13, avg_ep_correct  0.4062, train loss -0.0629 ]\n\n0it [00:00, ?it/s]\n1it [00:00, 24.49it/s]\n07/16/2025 07:21:57 PM: [ Hits@1:  1.0000 ]\n07/16/2025 07:21:57 PM: [ Hits@3:  1.0000 ]\n07/16/2025 07:21:57 PM: [ Hits@5:  1.0000 ]\n07/16/2025 07:21:57 PM: [ Hits@10:  1.0000 ]\n07/16/2025 07:21:57 PM: [ Hits@20:  1.0000 ]\n07/16/2025 07:21:57 PM: [ auc:  1.0000 ]\n07/16/2025 07:21:57 PM: [ Memory usage: 981270528 (kb) ]\n07/16/2025 07:21:57 PM: [ Creating TF graph... ]\n07/16/2025 07:21:57 PM: [ TF Graph creation done.. ]\n\n0it [00:00, ?it/s]\n0it [00:00, ?it/s]\nTraceback (most recent call last):\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 1407, in _do_call\n    return fn(*args)\n           ^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 1390, in _run_fn\n    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 1483, in _call_tf_sessionrun\n    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ntensorflow.python.framework.errors_impl.FailedPreconditionError: Could not find variable policy_steps_unroll_1/MLP_for_policy/dense_14/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/policy_steps_unroll_1/MLP_for_policy/dense_14/kernel)\n\t [[{{node policy_steps_unroll_1/MLP_for_policy/dense_14_1/Cast/ReadVariableOp}}]]\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py\", line 593, in <module>\n    trainer.test(sess, beam=True, print_paths=True, save_model=False)\n  File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py\", line 338, in test\n    loss, agent_mem, test_scores, test_action_idx, chosen_relation = sess.run(\n                                                                     ^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 977, in run\n    result = self._run(None, fetches, feed_dict, options_ptr,\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 1220, in _run\n    results = self._do_run(handle, final_targets, final_fetches,\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 1400, in _do_run\n    return self._do_call(_run_fn, feeds, fetches, targets, options,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/client/session.py\", line 1426, in _do_call\n    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ntensorflow.python.framework.errors_impl.FailedPreconditionError: Graph execution error:\n\nDetected at node 'policy_steps_unroll_1/MLP_for_policy/dense_14_1/Cast/ReadVariableOp' defined at (most recent call last):\n    File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py\", line 582, in <module>\n    File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py\", line 139, in initialize\n    File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/agent.py\", line 104, in step\n    File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/agent.py\", line 72, in policy_MLP\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/layer.py\", line 936, in __call__\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/ops/operation.py\", line 58, in __call__\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py\", line 151, in call\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/ops/numpy.py\", line 4021, in matmul\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/numpy.py\", line 490, in matmul\n    File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/core.py\", line 84, in __tf_tensor__\nNode: 'policy_steps_unroll_1/MLP_for_policy/dense_14_1/Cast/ReadVariableOp'\nCould not find variable policy_steps_unroll_1/MLP_for_policy/dense_14/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/policy_steps_unroll_1/MLP_for_policy/dense_14/kernel)\n\t [[{{node policy_steps_unroll_1/MLP_for_policy/dense_14_1/Cast/ReadVariableOp}}]]\n\nOriginal stack trace for 'policy_steps_unroll_1/MLP_for_policy/dense_14_1/Cast/ReadVariableOp':\n  File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py\", line 582, in <module>\n  File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/trainer.py\", line 139, in initialize\n  File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/agent.py\", line 104, in step\n  File \"/Users/u1770777/Library/CloudStorage/GoogleDrive-giovanni.montana@gmail.com/My Drive/mycode/GraphReasoningRL/minerva/comparison/tf_patched/model/agent.py\", line 72, in policy_MLP\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/layer.py\", line 936, in __call__\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/ops/operation.py\", line 58, in __call__\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py\", line 151, in call\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/ops/numpy.py\", line 4021, in matmul\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/numpy.py\", line 490, in matmul\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py\", line 1260, in op_dispatch_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/math_ops.py\", line 1012, in cast\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/ops.py\", line 736, in convert_to_tensor\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/tensor_conversion_registry.py\", line 209, in convert\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/core.py\", line 84, in __tf_tensor__\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/util/dispatch.py\", line 1260, in op_dispatch_handler\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/tensor_conversion.py\", line 161, in convert_to_tensor_v2_with_dispatch\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/tensor_conversion.py\", line 171, in convert_to_tensor_v2\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/tensor_conversion_registry.py\", line 234, in convert\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 2378, in _dense_var_to_tensor\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 1624, in _dense_var_to_tensor\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 658, in value\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 843, in _read_variable_op\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 833, in read_and_set_handle\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py\", line 548, in read_variable_op\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/ops.py\", line 2705, in _create_op_internal\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/framework/ops.py\", line 1200, in from_node_def\n\n",
  "metrics": {
    "hits@1": 1.0,
    "hits@3": 1.0,
    "hits@5": 1.0,
    "hits@10": 1.0,
    "auc": 1.0
  },
  "fixes_completed": [
    "Python 2 to 3 syntax conversion",
    "Import path fixes",
    "scipy dependency replacement",
    "TensorFlow 1.x API compatibility",
    "tf.contrib replacements",
    "Keras 3 LSTM compatibility",
    "RNN cell API changes",
    "Division operator fixes",
    "Checkpoint loading fixes"
  ]
}